# Generated by Django 6.0.4 on 2026-04-09 16:11

import django.contrib.auth.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('monthly_budget', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('profession', models.CharField(blank=True, max_length=150, null=True)),
                ('financial_goal', models.TextField(blank=True, null=True)),
                ('last_ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('location_data', models.JSONField(blank=True, default=dict)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('auth_provider', models.CharField(choices=[('EMAIL', 'Email'), ('GOOGLE', 'Google')], default='EMAIL', help_text="Méthode d'inscription utilisée par l'utilisateur", max_length=10)),
                ('google_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AppFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(help_text='Note de 1 à 5 étoiles', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField(blank=True, help_text='Commentaire facultatif', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseIntention',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=100)),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product_category', models.CharField(max_length=100)),
                ('product_image', models.ImageField(blank=True, null=True, upload_to='product_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ai_verdict', models.CharField(blank=True, choices=[('BUY', 'Acheter'), ('CALM', 'Calm Down (Réflexion)'), ('ABANDON', 'Abandonner')], help_text="Le verdict rendu par l'IA", max_length=10, null=True)),
                ('ai_reasoning', models.TextField(blank=True, help_text="L'argumentaire généré par l'IA pour justifier son verdict", null=True)),
                ('user_final_decision', models.CharField(blank=True, choices=[('BUY', 'Acheter'), ('CALM', 'Calm Down (Réflexion)'), ('ABANDON', 'Abandonner')], help_text="La décision finale prise par l'utilisateur", max_length=10, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_intentions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReflectionQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=300)),
                ('user_answer', models.CharField(blank=True, choices=[('YES', 'Oui'), ('NO', 'Non'), ('IDK', 'Je ne sais pas')], max_length=3, null=True)),
                ('purchase_intention', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='api.purchaseintention')),
            ],
        ),
        migrations.CreateModel(
            name='ErrorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('WARN', 'Avertissement'), ('ERROR', 'Erreur'), ('CRIT', 'Critique (Crash)')], default='ERROR', max_length=5)),
                ('error_message', models.TextField()),
                ('endpoint_url', models.CharField(blank=True, help_text="L'URL de l'API où l'erreur s'est produite", max_length=255, null=True)),
                ('is_resolved', models.BooleanField(default=False, help_text='Indique si le développeur a corrigé ce bug')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', '-created_at'], name='api_errorlo_user_id_58b232_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='purchaseintention',
            index=models.Index(fields=['user', '-created_at'], name='api_purchas_user_id_d40abc_idx'),
        ),
    ]
