# Generated by Django 6.0.4 on 2026-04-20 09:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='purchaseintention',
            name='has_similar_item',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='purchaseintention',
            name='urgency_level',
            field=models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='purchaseintention',
            name='usage_frequency',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
