# Generated by Django 6.0.4 on 2026-05-02 17:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_customuser_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appfeedback',
            name='subject',
            field=models.CharField(blank=True, help_text='Objet du message', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseintention',
            name='ai_verdict',
            field=models.CharField(blank=True, choices=[('BUY', 'Acheter'), ('CALM', 'Calm Down (Réflexion)'), ('ABANDON', 'Abandonner'), ('UNKOWN', 'Inconnu')], help_text="Le verdict rendu par l'IA", max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseintention',
            name='user_final_decision',
            field=models.CharField(blank=True, choices=[('BUY', 'Acheter'), ('CALM', 'Calm Down (Réflexion)'), ('ABANDON', 'Abandonner'), ('UNKOWN', 'Inconnu')], default='UNKOWN', help_text="La décision finale prise par l'utilisateur", max_length=10, null=True),
        ),
        migrations.CreateModel(
            name='SavingsGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal_name', models.CharField(help_text='Ex: Nouvel Ordinateur', max_length=150)),
                ('target_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('saved_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='savings_goals', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
