# Generated by Django 6.0.4 on 2026-05-02 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_appfeedback_subject_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='cooldown_preference',
            field=models.IntegerField(default=24, help_text='Temps de réflexion par défaut en heures (12, 24, 48, 72)'),
        ),
        migrations.AddField(
            model_name='purchaseintention',
            name='cooldown_expires_at',
            field=models.DateTimeField(blank=True, help_text="Date d'expiration de la période de réflexion", null=True),
        ),
    ]
