# Generated by Django 6.0.4 on 2026-05-03 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_customuser_evaluation_rigor'),
    ]

    operations = [
        migrations.AddField(
            model_name='reflectionquestion',
            name='ai_options',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='reflectionquestion',
            name='user_answer',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
