# Generated by Django 6.0.4 on 2026-05-03 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_reflectionquestion_ai_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='preferred_currency',
            field=models.CharField(default='TND', max_length=3),
        ),
    ]
