# Generated by Django 6.0.4 on 2026-05-03 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_customuser_preferred_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseintention',
            name='is_incoherent_bypassed',
            field=models.BooleanField(default=False, help_text="Indique si l'utilisateur a forcé la création malgré l'alerte d'incohérence"),
        ),
    ]
