# Generated by Django 6.0.4 on 2026-05-05 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_purchaseintention_is_incoherent_bypassed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseintention',
            name='product_category',
            field=models.CharField(choices=[('Smartphones', 'Smartphones'), ('Ordinateurs & Tablettes', 'Ordinateurs & Tablettes'), ('Audio & Écouteurs', 'Audio & Écouteurs'), ('Accessoires Tech (Coques, Câbles...)', 'Accessoires Tech (Coques, Câbles...)'), ('Consoles de jeux', 'Consoles de jeux'), ('Jeux vidéo', 'Jeux vidéo'), ('Vêtements', 'Vêtements'), ('Chaussures & Sneakers', 'Chaussures & Sneakers'), ('Sacs & Maroquinerie', 'Sacs & Maroquinerie'), ('Bijoux & Montres', 'Bijoux & Montres'), ('Accessoires de Mode', 'Accessoires de Mode'), ("Décoration d'intérieur", "Décoration d'intérieur"), ('Meubles', 'Meubles'), ("Bougies & Parfums d'ambiance", "Bougies & Parfums d'ambiance"), ('Ustensiles de cuisine & Vaisselle', 'Ustensiles de cuisine & Vaisselle'), ('Petit Électroménager', 'Petit Électroménager'), ('Gros Électroménager', 'Gros Électroménager'), ('Maquillage & Cosmétiques', 'Maquillage & Cosmétiques'), ('Soins de la peau', 'Soins de la peau'), ('Parfums', 'Parfums'), ('Soins des cheveux', 'Soins des cheveux'), ('Équipement de sport', 'Équipement de sport'), ('Objets de collection & Figurines', 'Objets de collection & Figurines'), ('Livres, Mangas & BD', 'Livres, Mangas & BD'), ('Art & Loisirs créatifs', 'Art & Loisirs créatifs'), ('Restaurants & Livraison', 'Restaurants & Livraison'), ('Cafés & Salons de thé', 'Cafés & Salons de thé'), ('Snacks & Alcool', 'Snacks & Alcool'), ('Abonnements & Logiciels', 'Abonnements & Logiciels'), ('Achats in-app & Microtransactions', 'Achats in-app & Microtransactions'), ('Autre', 'Autre')], default='Autre', max_length=100),
        ),
    ]
