# Generated by Django 6.0.4 on 2026-05-06 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_customuser_birth_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='wants_cooldown_reminders',
            field=models.BooleanField(default=True, help_text='Recevoir une alerte avant la fin de la période de réflexion'),
        ),
        migrations.AddField(
            model_name='purchaseintention',
            name='reminder_sent',
            field=models.BooleanField(default=False, help_text="Indique si l'e-mail de rappel de 2h a déjà été envoyé"),
        ),
    ]
