# Generated by Django 6.0.4 on 2026-05-06 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_customuser_wants_cooldown_reminders_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='history_cleared_at',
            field=models.DateTimeField(blank=True, help_text="Date de la dernière réinitialisation de l'historique (Soft Delete)", null=True),
        ),
    ]
