# Generated by Django 6.0.4 on 2026-05-07 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_aiwarninglog'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseintention',
            name='wait_chosen_at',
            field=models.DateTimeField(blank=True, help_text="Date à laquelle l'utilisateur a cliqué sur 'Attendre' pour la première fois", null=True),
        ),
    ]
