# Generated by Django 6.0.4 on 2026-05-07 10:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_purchaseintention_wait_chosen_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='errorlog',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_error_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='errorlog',
            name='http_method',
            field=models.CharField(blank=True, choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('PATCH', 'PATCH'), ('DELETE', 'DELETE'), ('OPTIONS', 'OPTIONS'), ('HEAD', 'HEAD')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='errorlog',
            name='priority',
            field=models.CharField(choices=[('LOW', 'Basse'), ('MEDIUM', 'Moyenne'), ('HIGH', 'Haute'), ('CRITICAL', 'Critique')], default='MEDIUM', max_length=20),
        ),
        migrations.AddField(
            model_name='errorlog',
            name='resolution_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='errorlog',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='errorlog',
            name='stack_trace',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='errorlog',
            name='status',
            field=models.CharField(choices=[('NEW', 'Nouveau'), ('TRIAGED', 'Trié'), ('IN_PROGRESS', 'En cours'), ('FIXED', 'Corrigé'), ('VERIFIED', 'Vérifié'), ('CLOSED', 'Fermé')], default='NEW', max_length=20),
        ),
        migrations.AddIndex(
            model_name='errorlog',
            index=models.Index(fields=['status', 'priority'], name='api_errorlo_status_5f5044_idx'),
        ),
    ]
