# Generated by Django 6.0.4 on 2026-05-07 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_errorlog_assigned_to_errorlog_http_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='monthly_budget',
            field=models.CharField(blank=True, choices=[('Je préfère ne pas répondre', 'Je préfère ne pas répondre'), ('Moins de 500', 'Moins de 500'), ('500 - 1 000', '500 - 1 000'), ('1 000 - 2 000', '1 000 - 2 000'), ('2 000 - 3 500', '2 000 - 3 500'), ('3 500 - 5 000', '3 500 - 5 000'), ('5 000 - 8 000', '5 000 - 8 000'), ('8 000 - 15 000', '8 000 - 15 000'), ('15 000+', '15 000+')], max_length=50, null=True),
        ),
    ]
