# Generated by Django 6.0.4 on 2026-05-07 16:14

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_customuser_monthly_budget'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='socio_professional_categories',
            field=models.JSONField(blank=True, default=api.models.default_socio_pro, help_text='Catégories socio-professionnelles (max 3)'),
        ),
    ]
