# Generated by Django 6.0.4 on 2026-05-08 20:39

import api.models
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20260507_1714'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='financial_goal',
        ),
        migrations.AddField(
            model_name='customuser',
            name='financial_goals',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=list, null=True, size=3),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_onboarded',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='socio_professional_categories',
            field=models.JSONField(blank=True, default=api.models.default_socio_pro, help_text='Catégories socio-professionnelles (max 3)', null=True),
        ),
    ]
