# Generated by Django 6.0.4 on 2026-05-09 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_remove_customuser_financial_goal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='monthly_budget',
            field=models.CharField(blank=True, choices=[('Moins de 500', 'Moins de 500'), ('500 - 1 000', '500 - 1 000'), ('1 000 - 2 000', '1 000 - 2 000'), ('2 000 - 3 500', '2 000 - 3 500'), ('3 500 - 5 000', '3 500 - 5 000'), ('5 000 - 8 000', '5 000 - 8 000'), ('8 000 - 15 000', '8 000 - 15 000'), ('15 000+', '15 000+'), ('Je préfère ne pas répondre', 'Je préfère ne pas répondre')], max_length=50, null=True),
        ),
    ]
