# Generated by Django 6.0.4 on 2026-05-22 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_customuser_current_balance_incomestream_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incomestream',
            name='next_payment_date',
            field=models.DateField(blank=True, help_text='Date du prochain versement', null=True),
        ),
    ]
