# Generated by Django 6.0.4 on 2026-05-22 15:53

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_alter_incomestream_next_payment_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecurringChargeBlueprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ex: Électricité, Internet, Loyer', max_length=150)),
                ('is_fixed', models.BooleanField(default=True, help_text='Indique si le montant est fixe ou variable')),
                ('exact_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('min_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('max_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('due_day', models.IntegerField(help_text='Le jour du mois où la charge est exigible', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)])),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charge_blueprints', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MonthlyChargeLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('is_fixed', models.BooleanField(default=True)),
                ('max_amount', models.DecimalField(decimal_places=2, help_text='Le montant maximal verrouillé dans le coffre', max_digits=10)),
                ('min_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('exact_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('due_date', models.DateField(help_text="Date précise d'échéance pour ce mois-ci")),
                ('is_paid', models.BooleanField(default=False)),
                ('actual_amount_paid', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_ledgers', to=settings.AUTH_USER_MODEL)),
                ('blueprint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_records', to='api.recurringchargeblueprint')),
            ],
            options={
                'ordering': ['due_date'],
                'unique_together': {('blueprint', 'due_date')},
            },
        ),
    ]
