# Generated by Django 6.0.4 on 2026-05-22 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_recurringchargeblueprint_monthlychargeledger'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionhistory',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='transactionhistory',
            name='is_essential',
            field=models.BooleanField(default=False),
        ),
    ]
