# Generated by Django 6.0.4 on 2026-05-23 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_budgetenvelope'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseintention',
            name='wallet_type',
            field=models.CharField(default='main', help_text="Indique la source de financement ('main' pour solde principal, 'env_X' pour une enveloppe)", max_length=50),
        ),
    ]
