# Generated by Django 6.0.4 on 2026-05-23 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_purchaseintention_wallet_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetenvelope',
            name='total_spent',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Montant déjà dépensé dans cette enveloppe', max_digits=10),
        ),
    ]
