# Generated by Django 6.0.4 on 2026-05-31 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_budgetenvelope_total_spent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='monthlychargeledger',
            old_name='actual_amount_paid',
            new_name='actual_amount',
        ),
        migrations.RenameField(
            model_name='monthlychargeledger',
            old_name='max_amount',
            new_name='provisioned_amount',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='monthly_budget',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='profession',
        ),
        migrations.RemoveField(
            model_name='monthlychargeledger',
            name='exact_amount',
        ),
        migrations.RemoveField(
            model_name='monthlychargeledger',
            name='is_fixed',
        ),
        migrations.RemoveField(
            model_name='monthlychargeledger',
            name='is_paid',
        ),
        migrations.RemoveField(
            model_name='monthlychargeledger',
            name='min_amount',
        ),
        migrations.RemoveField(
            model_name='monthlychargeledger',
            name='user',
        ),
        migrations.RemoveField(
            model_name='savingsgoal',
            name='saved_amount',
        ),
        migrations.AddConstraint(
            model_name='recurringchargeblueprint',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('exact_amount__isnull', False), ('is_fixed', True), ('max_amount__isnull', True), ('min_amount__isnull', True)), models.Q(('exact_amount__isnull', True), ('is_fixed', False), ('max_amount__isnull', False), ('min_amount__isnull', False)), _connector='OR'), name='valid_amount_configuration'),
        ),
    ]
