# Generated by Django 6.0.4 on 2026-06-10 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_alter_incomestream_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='incomestream',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
